services:

    amulen.shop.form.product:
        class: Flowcode\ShopBundle\Form\ProductType
        tags:
            - { name: form.type, alias: flowcode_shopbundle_product }

    amulen.shop.product.service:
        class: Flowcode\ShopBundle\Service\ProductService
        arguments: ['@service_container']

    amulen.shop.form.productorder:
        class: Flowcode\ShopBundle\Form\ProductOrderType
        tags:
            - { name: form.type, alias: amulen_shopbundle_productorder }

    symfony.form.type.tree:
       class: Yavin\Symfony\Form\Type\TreeType
       arguments: [ "@property_accessor" ]
       tags:
           - { name: form.type, alias: y_tree }
    symfony.form.type_guesser.tree:
       class: Yavin\Symfony\Form\Type\TreeTypeGuesser
       arguments: [ "@doctrine" ]
       tags:
           - { name: form.type_guesser }

    amulen.shop.form.product.gallery:
        class: Flowcode\ShopBundle\Form\ProductGalleryItemType
        tags:
            - { name: form.type, alias: flowcode_shopbundle_product_gallery }

    amulen.shop.form.brand:
        class: Flowcode\ShopBundle\Form\BrandType
        tags:
            - { name: form.type, alias: flowcode_shopbundle_brand }
