services:

    amulen.shop.form.product:
        class: Flowcode\ShopBundle\Form\ProductType
        arguments: ['@amulen.classification.category']
        tags:
            - { name: form.type, alias: flowcode_shopbundle_product }

    amulen.shop.form.productorder:
        class: Flowcode\ShopBundle\Form\ProductOrderType
        tags:
            - { name: form.type, alias: amulen_shopbundle_productorder }

    symfony.form.type.tree:
       class: Yavin\Symfony\Form\Type\TreeType
       arguments: [ "@property_accessor" ]
       tags:
           - { name: form.type, alias: y_tree }
    symfony.form.type_guesser.tree:
       class: Yavin\Symfony\Form\Type\TreeTypeGuesser
       arguments: [ "@doctrine" ]
       tags:
           - { name: form.type_guesser }

    amulen.shop.form.product.gallery:
        class: Flowcode\ShopBundle\Form\ProductGalleryItemType
        tags:
            - { name: form.type, alias: flowcode_shopbundle_product_gallery }

    amulen.shop.form.brand:
        class: Flowcode\ShopBundle\Form\BrandType
        tags:
            - { name: form.type, alias: flowcode_shopbundle_brand }

    amulen.shop.showmenu_eventsubscriber:
        class: Flowcode\ShopBundle\Event\ShowMenuSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }

    amulen.shop.listplugins_eventsubscriber:
        class: Flowcode\ShopBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }

    amulen.shop.repository.order:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Amulen\ShopBundle\Entity\ProductOrder

    amulen.shop.repository.order_status:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Amulen\ShopBundle\Entity\ProductOrderStatus

    amulen.shop.repository.order.item:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Amulen\ShopBundle\Entity\ProductOrderItem

    amulen.shop.product:
        class: Flowcode\ShopBundle\Service\ProductService
        arguments: ["@doctrine.orm.entity_manager"]

    amulen.shop.order:
        class: Flowcode\ShopBundle\Service\ProductOrderService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@amulen.shop.repository.order"
          - "@amulen.shop.repository.order_status"
          - "@event_dispatcher"

    amulen.shop.order.item:
        class: Flowcode\ShopBundle\Service\ProductOrderItemService
        arguments: ["@doctrine.orm.entity_manager", "@amulen.shop.repository.order.item"]
