<?php

namespace Flowcode\ShopBundle\Repository;
use Flowcode\ShopBundle\Form\Type\InventoryItemsPartialType;
use Flowcode\ShopBundle\Model\Product;

/**
 * InventoryItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryItemRepository extends \Doctrine\ORM\EntityRepository
{
}
