<?php

namespace Flowcode\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductOrderStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductOrderStatusRepository extends EntityRepository
{

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllQB()
    {
        $qb = $this->createQueryBuilder('os');
        return $qb;
    }

    /**
     * @param $filter
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllFilteredQB($filter)
    {
        $qb = $this->findAllQB();

        if ($filter['q']) {
            $qb->andwhere('os.name LIKE :name')->setParameter('name', '%' . $filter['q'] . '%');
        }

        return $qb;
    }
}
