<?php

namespace Flowcode\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductItemFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemFieldRepository extends EntityRepository
{
    public function findByCategories($category)
    {
        $qb = $this->createQueryBuilder('pif');
        $qb->join('pif.category', 'c');
        $qb->where('c.id = :category')->setParameter('category', $category);

        return $qb->getQuery()->getResult();
    }
}
