<?php

namespace Flowcode\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductItemFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemFieldRepository extends EntityRepository
{
    public function findByCategories($categoryIds)
    {
        $qb = $this->createQueryBuilder('pif');
        $qb->join('pif.category', 'c');
        $qb->where('c.id in (:category_ids)')->setParameter('category_ids', $categoryIds);

        return $qb->getQuery()->getResult();
    }
}
