<?php

namespace Flowcode\ShopBundle\Repository;

/**
 * ShopSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
