<?php

namespace Flowcode\ShopBundle\Repository;

/**
 * StockTransferItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTransferItemRepository extends \Doctrine\ORM\EntityRepository
{
}
