<?php

namespace Flowcode\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Flowcode\ShopBundle\Entity\StockChangeLog;

/**
 * StockChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockChangeLogRepository extends EntityRepository
{
    public function save(StockChangeLog $stockChangeLog)
    {
        $this->_em->persist($stockChangeLog);
        $this->_em->flush();
    }

    public function findAllQB()
    {
        $qb = $this->createQueryBuilder('scl');
        return $qb;
    }

    public function findAllFilteredQB($filter)
    {
        $qb = $this->findAllQB();
        $qb->leftJoin('scl.product', 'p');
        $qb->leftJoin('scl.warehouse', 'w');

        if (isset($filter['product'])) {
            $qb->andWhere('p.id =:product_id')->setParameter('product_id', $filter['product']);
        }
        if (isset($filter['warehouse'])) {
            $qb->andWhere('w.id = :warehouse_id')->setParameter('warehouse_id', $filter['warehouse']);
        }

        return $qb;
    }
}
